version: "3.6"

networks:
  proxy:
    external: true
    name: swarm-proxy
    driver: overlay
  backend:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  swag:
    image: linuxserver/swag:version-1.17.0
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${PUBLIC_DOMAIN}
      - EXTRA_DOMAINS=${INTERNAL_DOMAIN}
      - SUBDOMAINS=wildcard
      - DNSPLUGIN=cloudflare
      - VALIDATION=dns
      - EMAIL=${EMAIL}
      - ONLY_SUBDOMAINS=true
      - STAGING=false
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - proxy
      - backend

  homer:
    image: ghcr.io/georgegedox/homergx:latest
    container_name: homer
    environment:
      - UID=${PUID}
      - GID=${PGID}
    volumes:
      - ./homer:/www/assets
    restart: unless-stopped
    networks:
      - backend

  bitwarden:
    image: vaultwarden/server:1.22.1
    container_name: bitwarden
    environment:
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
    volumes:
      - ./bitwarden:/data
    restart: unless-stopped
    networks:
      - backend

  redbot:
    image: phasecorex/red-discordbot
    container_name: redbot
    restart: unless-stopped
    environment:
      - TOKEN=${DISCORD_BOT_TOKEN}
      - PREFIX=!
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes: 
      - ./redbot:/data
    networks:
    - backend

  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    volumes: 
      - ./adguard/config:/opt/adguardhome/conf
      - ./adguard/workdir:/opt/adguardhome/work
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
    networks:
      - backend

  adguardhome-sync:
    image: ghcr.io/linuxserver/adguardhome-sync
    container_name: adguardhome-sync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./adguard_sync:/config
    restart: unless-stopped
    networks:
      - proxy
      - backend

  grafana:
    container_name: grafana
    image: grafana/grafana:8.0.4
    restart: unless-stopped
    environment:
      - GF_PATHS_CONFIG=/var/lib/grafana/grafana.ini
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - backend

  loki:
    container_name: loki
    image: grafana/loki:2.4.1
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
      - ./loki/data:/data/loki
    networks:
      - backend

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.28.1
    restart: unless-stopped
    volumes: 
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    networks:
      - backend

  postgresql:
    container_name: postgresql
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGSQL_PASSWORD}
      - POSTGRES_USER=root
      - POSTGRES_DB=authentik
    networks:
      - backend
      
  authentik-redis:
    image: redis:6.2.3-alpine3.13
    container_name: authentik-redis
    restart: unless-stopped
    networks:
      - backend

  authentik:
    container_name: authentik
    image: ghcr.io/goauthentik/server:2021.10.1
    restart: unless-stopped
    command: server
    volumes:
      - ./authentik/media:/media
      - ./authentik/custom-templates:/templates
    environment: 
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=root
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PGSQL_PASSWORD}
    env_file:
      - .env
    networks:
      - backend

  authentik-worker:
    container_name: authentik-worker
    image: ghcr.io/goauthentik/server:2021.10.1
    restart: unless-stopped
    command: worker
    user: root
    volumes:
      - ./authentik/media:/media
      - ./authentik/custom-templates:/templates
      - ./authentik/backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - AUTHENTIK_REDIS__HOST=authentik-redis
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=root
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PGSQL_PASSWORD}
    env_file:
      - .env
    networks:
      - backend

  authentik-proxy:
    container_name: authentik-proxy
    image: ghcr.io/goauthentik/proxy:2021.10.1
    restart: unless-stopped
    environment:
      - AUTHENTIK_HOST=${AUTHENTIK_OUTPOST__HOST}
      - AUTHENTIK_INSECURE="false"
      - AUTHENTIK_TOKEN=${AUTHENTIK_PROXY__TOKEN}
    networks:
      - backend

  authentik-ldap:
    container_name: authentik-ldap
    image: ghcr.io/goauthentik/ldap:2021.10.1
    restart: unless-stopped
    ports: 
      - 389:3389
    environment:
      - AUTHENTIK_HOST=${AUTHENTIK_OUTPOST__HOST}
      - AUTHENTIK_INSECURE="false"
      - AUTHENTIK_TOKEN=${AUTHENTIK_LDAP__TOKEN}
    networks:
      - backend

  speedtest:
    ports:
      - 9798:9798
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest
    restart: unless-stopped
    networks:
      - backend

  blackbox:
    ports:
      - 9115:9115
    image: prom/blackbox-exporter
    container_name: blackbox
    restart: unless-stopped
    volumes:
      - ./blackbox/config:/config
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - backend
